INSERT INTO quotes (user_id, original_text, cleaned_text_en, cleaned_text_zh_tw, cleaned_text_zh_cn) VALUES
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Stillness reveals what noise conceals.', 'Stillness reveals what noise conceals.', '安靜顯現出喧囂所掩蓋的。', '安静显现出喧嚣所掩盖的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Emotions are visitors that come and go.', 'Emotions are visitors that come and go.', '情緒是來來去去的訪客。', '情绪是来来去去的访客。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The space between thoughts is where peace lives.', 'The space between thoughts is where peace lives.', '思緒之間的空白，是平靜所在。', '思绪之间的空白，是平静所在。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Acceptance is not resignation; it is clarity.', 'Acceptance is not resignation; it is clarity.', '接納不是放棄，而是清晰。', '接纳不是放弃，而是清晰。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Inner calm is not the absence of storms, but the ability to remain steady within them.', 'Inner calm is not the absence of storms, but the ability to remain steady within them.', '內在平靜不是沒有風暴，而是在風暴中保持穩定。', '内在平静不是没有风暴，而是在风暴中保持稳定。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Feelings pass through us like clouds through the sky.', 'Feelings pass through us like clouds through the sky.', '感受如雲朵般穿過我們，如同穿過天空。', '感受如云朵般穿过我们，如同穿过天空。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment holds everything we need.', 'The present moment holds everything we need.', '當下這一刻包含了我們所需的一切。', '当下这一刻包含了我们所需的一切。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Peace comes from understanding, not from changing what is.', 'Peace comes from understanding, not from changing what is.', '平靜來自理解，而非改變現狀。', '平静来自理解，而非改变现状。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'We are not our thoughts; we are the awareness that observes them.', 'We are not our thoughts; we are the awareness that observes them.', '我們不是我們的念頭，而是觀察念頭的覺知。', '我们不是我们的念头，而是观察念头的觉知。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Stability grows from roots that reach deep into acceptance.', 'Stability grows from roots that reach deep into acceptance.', '穩定來自深深扎根於接納的根。', '稳定来自深深扎根于接纳的根。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The heart knows its own rhythm when the mind is quiet.', 'The heart knows its own rhythm when the mind is quiet.', '當心靈安靜時，心知道自己的節奏。', '当心灵安静时，心知道自己的节奏。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Resistance creates tension; allowing creates space.', 'Resistance creates tension; allowing creates space.', '抗拒產生緊張，允許創造空間。', '抗拒产生紧张，允许创造空间。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Emotional weather changes, but the sky remains the same.', 'Emotional weather changes, but the sky remains the same.', '情緒的天氣會變化，但天空依然如故。', '情绪的天气会变化，但天空依然如故。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Stillness is not emptiness; it is fullness of presence.', 'Stillness is not emptiness; it is fullness of presence.', '靜止不是空無，而是存在的豐盈。', '静止不是空无，而是存在的丰盈。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The depth of calm is found in the simplicity of being.', 'The depth of calm is found in the simplicity of being.', '平靜的深度存在於存在的簡單中。', '平静的深度存在于存在的简单中。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Feelings are information, not instructions.', 'Feelings are information, not instructions.', '感受是資訊，不是指令。', '感受是信息，不是指令。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Inner stability is built moment by moment, breath by breath.', 'Inner stability is built moment by moment, breath by breath.', '內在穩定是一刻一刻、一呼一吸建立起來的。', '内在稳定是一刻一刻、一呼一吸建立起来的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The calm center remains untouched by the outer chaos.', 'The calm center remains untouched by the outer chaos.', '平靜的中心不受外在混亂影響。', '平静的中心不受外在混乱影响。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Understanding dissolves judgment; presence dissolves anxiety.', 'Understanding dissolves judgment; presence dissolves anxiety.', '理解消融判斷，臨在消融焦慮。', '理解消融判断，临在消融焦虑。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Peace is not a destination; it is the quality of the journey itself.', 'Peace is not a destination; it is the quality of the journey itself.', '平靜不是目的地，而是旅程本身的品質。', '平静不是目的地，而是旅程本身的品质。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Self-compassion is the foundation of inner strength.', 'Self-compassion is the foundation of inner strength.', '自我慈悲是內在力量的基礎。', '自我慈悲是内在力量的基础。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'What we resist persists; what we accept transforms.', 'What we resist persists; what we accept transforms.', '我們抗拒的會持續，我們接納的會轉化。', '我们抗拒的会持续，我们接纳的会转化。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment is the only place where life happens.', 'The present moment is the only place where life happens.', '當下是生命唯一發生的地方。', '当下是生命唯一发生的地方。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Vulnerability is the birthplace of authentic connection.', 'Vulnerability is the birthplace of authentic connection.', '脆弱是真實連結的誕生地。', '脆弱是真实连结的诞生地。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Rest is not a reward; it is a requirement for wholeness.', 'Rest is not a reward; it is a requirement for wholeness.', '休息不是獎勵，而是完整的必需。', '休息不是奖励，而是完整的必需。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The mind settles when we stop trying to control it.', 'The mind settles when we stop trying to control it.', '當我們停止試圖控制時，心靈會安定下來。', '当我们停止试图控制时，心灵会安定下来。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Compassion for ourselves opens the door to compassion for others.', 'Compassion for ourselves opens the door to compassion for others.', '對自己的慈悲開啟了對他人慈悲的大門。', '对自己的慈悲开启了对他人慈悲的大门。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'In stillness, we find what we have been searching for in motion.', 'In stillness, we find what we have been searching for in motion.', '在靜止中，我們找到在行動中一直尋找的。', '在静止中，我们找到在行动中一直寻找的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The body remembers what the mind forgets.', 'The body remembers what the mind forgets.', '身體記住心靈遺忘的。', '身体记住心灵遗忘的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Gentleness with ourselves creates space for growth.', 'Gentleness with ourselves creates space for growth.', '對自己的溫柔為成長創造空間。', '对自己的温柔为成长创造空间。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Every emotion has a message; every feeling has a purpose.', 'Every emotion has a message; every feeling has a purpose.', '每種情緒都有訊息，每種感受都有目的。', '每种情绪都有信息，每种感受都有目的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The breath is the bridge between body and mind.', 'The breath is the bridge between body and mind.', '呼吸是身體與心靈之間的橋樑。', '呼吸是身体与心灵之间的桥梁。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Acceptance does not mean approval; it means acknowledgment.', 'Acceptance does not mean approval; it means acknowledgment.', '接納不意味著認同，而是承認。', '接纳不意味着认同，而是承认。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The quieter we become, the more we can hear.', 'The quieter we become, the more we can hear.', '我們越安靜，聽到的越多。', '我们越安静，听到的越多。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Self-acceptance is the first step toward transformation.', 'Self-acceptance is the first step toward transformation.', '自我接納是轉化的第一步。', '自我接纳是转化的第一步。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment is complete in itself.', 'The present moment is complete in itself.', '當下這一刻本身是完整的。', '当下这一刻本身是完整的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'We do not need to fix ourselves; we need to understand ourselves.', 'We do not need to fix ourselves; we need to understand ourselves.', '我們不需要修復自己，我們需要理解自己。', '我们不需要修复自己，我们需要理解自己。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Patience with ourselves is patience with life.', 'Patience with ourselves is patience with life.', '對自己的耐心就是對生命的耐心。', '对自己的耐心就是对生命的耐心。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The mind is like water; when still, it reflects clearly.', 'The mind is like water; when still, it reflects clearly.', '心靈如水，靜止時清晰映照。', '心灵如水，静止时清晰映照。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Emotional storms pass; the witness remains.', 'Emotional storms pass; the witness remains.', '情緒風暴會過去，見證者依然存在。', '情绪风暴会过去，见证者依然存在。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Self-kindness is not weakness; it is wisdom.', 'Self-kindness is not weakness; it is wisdom.', '對自己仁慈不是軟弱，而是智慧。', '对自己仁慈不是软弱，而是智慧。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The depth of our peace matches the depth of our acceptance.', 'The depth of our peace matches the depth of our acceptance.', '我們平靜的深度與接納的深度相符。', '我们平静的深度与接纳的深度相符。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Feelings are temporary; awareness is constant.', 'Feelings are temporary; awareness is constant.', '感受是暫時的，覺知是恆常的。', '感受是暂时的，觉知是恒常的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Rest is not laziness; it is restoration.', 'Rest is not laziness; it is restoration.', '休息不是懶惰，而是恢復。', '休息不是懒惰，而是恢复。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment is where we meet ourselves.', 'The present moment is where we meet ourselves.', '當下是我們與自己相遇的地方。', '当下是我们与自己相遇的地方。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Compassion begins with the person in the mirror.', 'Compassion begins with the person in the mirror.', '慈悲從鏡中的人開始。', '慈悲从镜中的人开始。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Stillness is the language of the soul.', 'Stillness is the language of the soul.', '靜止是靈魂的語言。', '静止是灵魂的语言。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'We cannot force peace; we can only allow it.', 'We cannot force peace; we can only allow it.', '我們無法強迫平靜，只能允許它。', '我们无法强迫平静，只能允许它。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The heart speaks in whispers; we must be quiet to hear it.', 'The heart speaks in whispers; we must be quiet to hear it.', '心以低語說話，我們必須安靜才能聽見。', '心以低语说话，我们必须安静才能听见。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Self-acceptance is not self-indulgence; it is self-respect.', 'Self-acceptance is not self-indulgence; it is self-respect.', '自我接納不是自我放縱，而是自我尊重。', '自我接纳不是自我放纵，而是自我尊重。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The space between stimulus and response is where freedom lives.', 'The space between stimulus and response is where freedom lives.', '刺激與回應之間的空間，是自由所在。', '刺激与回应之间的空间，是自由所在。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Inner peace is not the absence of conflict; it is the presence of understanding.', 'Inner peace is not the absence of conflict; it is the presence of understanding.', '內在平靜不是沒有衝突，而是有理解存在。', '内在平静不是没有冲突，而是有理解存在。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'We are enough, not because of what we do, but because of who we are.', 'We are enough, not because of what we do, but because of who we are.', '我們已經足夠，不是因為我們做了什麼，而是因為我們是誰。', '我们已经足够，不是因为我们做了什么，而是因为我们是谁。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment is the only time we have any power.', 'The present moment is the only time we have any power.', '當下是我們唯一有力量的時候。', '当下是我们唯一有力量的时候。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Self-compassion is the antidote to self-criticism.', 'Self-compassion is the antidote to self-criticism.', '自我慈悲是自我批評的解藥。', '自我慈悲是自我批评的解药。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The mind that is still knows what the busy mind cannot see.', 'The mind that is still knows what the busy mind cannot see.', '靜止的心靈知道忙碌心靈看不見的。', '静止的心灵知道忙碌心灵看不见的。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Acceptance is the first step toward change.', 'Acceptance is the first step toward change.', '接納是改變的第一步。', '接纳是改变的第一步。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The breath anchors us in the present moment.', 'The breath anchors us in the present moment.', '呼吸將我們錨定在當下。', '呼吸将我们锚定在当下。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'We do not need to be perfect to be worthy of love.', 'We do not need to be perfect to be worthy of love.', '我們不需要完美才值得被愛。', '我们不需要完美才值得被爱。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'Stillness is the foundation of all movement.', 'Stillness is the foundation of all movement.', '靜止是所有行動的基礎。', '静止是所有行动的基础。'),
('2ed78e5b-55f9-4343-ba1b-fadcc1dd2555', 'The present moment is where we find ourselves.', 'The present moment is where we find ourselves.', '當下是我們找到自己的地方。', '当下是我们找到自己的地方。');
